{% if cookiecutter.use_docker == 'yes' -%}
version: '3.8'

services:
  {% if cookiecutter.database == 'postgresql' -%}
  postgres:
    image: {% if cookiecutter.include_vector_search == 'y' %}pgvector/pgvector:pg16{% else %}postgres:16{% endif %}
    environment:
      POSTGRES_DB: {{cookiecutter.project_slug}}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  {%- elif cookiecutter.database == 'neo4j' -%}
  neo4j:
    image: neo4j:5.14
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
  {%- elif cookiecutter.database == 'mongodb' -%}
  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  {%- endif %}

  {% if cookiecutter.search_engine == 'elasticsearch' -%}
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  {%- endif %}

  {% if cookiecutter.api_framework != 'none' -%}
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      {% if cookiecutter.database == 'postgresql' -%}
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/{{cookiecutter.project_slug}}
      {%- elif cookiecutter.database == 'neo4j' -%}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      {%- elif cookiecutter.database == 'mongodb' -%}
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/{{cookiecutter.project_slug}}?authSource=admin
      {%- endif %}
      {% if cookiecutter.search_engine == 'elasticsearch' -%}
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      {%- endif %}
    depends_on:
      {% if cookiecutter.database == 'postgresql' -%}
      - postgres
      {%- elif cookiecutter.database == 'neo4j' -%}
      - neo4j
      {%- elif cookiecutter.database == 'mongodb' -%}
      - mongodb
      {%- endif %}
      {% if cookiecutter.search_engine == 'elasticsearch' -%}
      - elasticsearch
      {%- endif %}
  {%- endif %}

volumes:
  {% if cookiecutter.database == 'postgresql' -%}
  postgres_data:
  {%- elif cookiecutter.database == 'neo4j' -%}
  neo4j_data:
  {%- elif cookiecutter.database == 'mongodb' -%}
  mongo_data:
  {%- endif %}
  {% if cookiecutter.search_engine == 'elasticsearch' -%}
  es_data:
  {%- endif %}
{%- endif %}