[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{cookiecutter.project_slug}}"
version = "0.0.1"
description = "{{cookiecutter.description}}"
authors = [
    {name = "{{cookiecutter.author_name}}", email = "{{cookiecutter.author_email}}"},
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "loguru>=0.7.0",

    # Data source dependencies
    {% if cookiecutter.include_api_scraping == 'yes' -%}
    "httpx>=0.25.0",
    "requests>=2.31.0",
    {%- endif %}

    {% if cookiecutter.include_web_scraping == 'yes' -%}
    "beautifulsoup4>=4.12.0",
    "scrapy>=2.10.0",
    "selenium>=4.15.0",
    {%- endif %}

    # Storage dependencies
    {% if cookiecutter.database == 'postgresql' -%}
    "psycopg2-binary>=2.9.0",
    "sqlalchemy>=2.0.0",
    "alembic>=1.12.0",
    {% if cookiecutter.include_vector_search == 'yes' -%}
    "pgvector>=0.2.0",
    {%- endif %}
    {%- elif cookiecutter.database == 'neo4j' -%}
    "neo4j>=5.14.0",
    "py2neo>=2022.1.0",
    {%- elif cookiecutter.database == 'mongodb' -%}
    "motor>=3.3.0",
    "pymongo>=4.6.0",
    {%- elif cookiecutter.database == 'sqlite' -%}
    "sqlalchemy>=2.0.0",
    "aiosqlite>=0.19.0",
    {%- endif %}

    # Pipeline dependencies
    {% if cookiecutter.orchestrator == 'prefect' -%}
    "prefect>=2.14.0",
    {%- elif cookiecutter.orchestrator == 'airflow' -%}
    "apache-airflow>=2.7.0",
    {%- endif %}

    # API dependencies
    {% if cookiecutter.api_framework == 'fastapi' -%}
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    {%- elif cookiecutter.api_framework == 'flask' -%}
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    {%- elif cookiecutter.api_framework == 'django' -%}
    "django>=4.2.0",
    "djangorestframework>=3.14.0",
    {%- endif %}

    # Search dependencies
    {% if cookiecutter.search_engine == 'elasticsearch' -%}
    "elasticsearch>=8.11.0",
    {%- endif %}

    # Vector search dependencies
    {% if cookiecutter.include_vector_search == 'yes' -%}
    "sentence-transformers>=2.2.0",
    "numpy>=1.24.0",
    "faiss-cpu>=1.7.4",
    {%- endif %}

    # NLP dependencies
    {% if cookiecutter.include_nlp == 'yes' -%}
    "spacy>=3.7.0",
    "transformers>=4.35.0",
    "torch>=2.1.0",
    "scikit-learn>=1.3.0",
    {%- endif %}
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "black>=23.11.0",
    "isort>=5.12.0",
    "mypy>=1.7.0",
    "pre-commit>=3.5.0",
]

[project.scripts]
{{cookiecutter.project_slug}} = "{{cookiecutter.project_slug}}.cli:app"
